on:
  issues:
    types: [assigned]

jobs:
  issue-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: robvanderleek/create-issue-branch@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branchName: short
